name: Postman Functional/Integration + JMeter Stress Performance Test

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        shell: bash
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" >> .env
          echo "SESSION_SECRET=${SESSION_SECRET}" >> .env
          echo "EMAIL_USER=${EMAIL_USER}" >> .env
          echo "EMAIL_PASS=${EMAIL_PASS}" >> .env
          echo "PORT=5002" >> .env  # Ensure app runs on port 5002

      - name: Start Application
        run: node src/index.js &
        env:
          PORT: 5002  # Explicitly set the port

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:5002

      - name: Install OpenJDK 8
        run: sudo apt-get install -y openjdk-8-jdk

      - name: Setup JMeter
        uses: QAInsights/setup-jmeter@v3
        with:
          version: '5.5'

      - name: Configure JMeter XStream Security
        run: echo "xstream.security.allowAll=org.apache.jmeter.save.ScriptWrapper" >> $(jmeter -v | grep "Home:" | awk '{print $2}')/bin/jmeter.properties

      - name: Run JMeter Tests
        run: jmeter -n -t Jmeter/PostmanTest.jmx -l results.jtl
