name: Postman Test Workflow

on:
  push:
    branches:
      - main  # Run tests on push to main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" >> .env
          echo "SESSION_SECRET=${SESSION_SECRET}" >> .env
          echo "EMAIL_USER=${EMAIL_USER}" >> .env
          echo "EMAIL_PASS=${EMAIL_PASS}" >> .env
          echo "PORT=5002" >> .env  # Ensure app runs on port 5002

      - name: Start Application
        run: node src/index.js & 
        env:
          PORT: 5002  # Explicitly set the port

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:5002

      - name: Install Newman (Postman CLI)
        run: npm install -g newman
  
      - name: Run Postman Test 1
        run: newman run "Postman/AccountManagertest.postman_collection"
